export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const DEVICE_DESC_REPOSITORY = 'DEVICE_DESC_REPOSITORY'
export const JOB_REPOSITORY = 'JOB_REPOSITORY'
export const DEVICE_DESC_GROUP_REPOSITORY = 'DEVICE_DESC_GROUP_REPOSITORY'
